<?php

namespace App\Bundle\MainBundle\Entity\Record;

use Doctrine\ORM\EntityRepository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends EntityRepository
{
    /**
     * Save the given entity in database
     *
     * @param Record $record
     */
    public function save(Record $record)
    {
        $this->getEntityManager()->persist($record);
        $this->getEntityManager()->flush($record);
    }

    /**
     * Retrieve all world records
     *
     * @return Record[]
     */
    public function findAll()
    {
        $builder = $this->createQueryBuilder('record');
        $builder
            ->orderBy('record.createdAt', 'DESC')
        ;

        return $builder->getQuery()->getResult();
    }
}
