services:
    app_main.event.subscriber.submission:
        class: App\Bundle\MainBundle\Events\Submission\SubmissionSubscriber
        arguments: [@app_main.record.writer, @app_main.clock]
        tags:
            - { name: kernel.event_subscriber }
    app_main.run.thumbnailer:
        class: App\Bundle\MainBundle\Services\Run\Thumbnailer\YoutubeThumbnailer
    app_main.submission.autocompleter:
        class: App\Bundle\MainBundle\Services\Autocompleter\BusAutocompleter
        arguments: [@app_main.clock]
    app_main.submission.autocompleter.handler.speedruncom:
        class: App\Bundle\MainBundle\Services\Autocompleter\Handler\SpeedruncomHandler
        arguments: [@guzzle.client]
        tags:
            - { name: app_main.submission.autocompleter }
    app_main.submission.command.bus:
        class: App\Component\Command\Bus
        arguments: [[@app_main.submission.command.handler.refuse]]
    app_main.submission.command.handler.refuse:
        class: App\Component\Submission\RefuseHandler
        arguments: [@app_main.submission.writer]
    app_main.submission.entity_converter:
        class: App\Bundle\MainBundle\Services\Submission\EntityConverter
    app_main.submission.factory:
        class: App\Bundle\MainBundle\Services\Submission\SubmissionFactory
        arguments: [@app_main.clock, @app_main.run.thumbnailer]
    app_main.submission.reader:
        class: App\Bundle\MainBundle\Services\Submission\DoctrineReader
        arguments: [@doctrine.orm.entity_manager, @app_main.submission.entity_converter]
    app_main.submission.writer:
        class: App\Bundle\MainBundle\Services\Submission\DoctrineWriter
        arguments: [@doctrine.orm.entity_manager, @app_main.submission.entity_converter, @event_dispatcher]
