app_main_record:
    resource: "@AppMainBundle/Resources/config/Record/routing.yml"
    prefix:   /

app_main_security:
    resource: "@AppMainBundle/Resources/config/Security/routing.yml"
    prefix:   /

app_main_submission:
    resource: "@AppMainBundle/Resources/config/Submission/routing.yml"
    prefix:   /

app_main_homepage:
    path:     /
    defaults: { _controller: AppMainBundle:Default:index }
