services:
    app_main.clock:
        class: App\Component\Clock\Clock
    app_main.submission.factory:
        class: App\Bundle\MainBundle\Services\Submission\SubmissionFactory
        arguments: [@app_main.clock]
    app_main.submission.writer:
        class: App\Bundle\MainBundle\Services\Submission\SubmissionWriter
