services:
    app_main.clock:
        class: App\Component\Clock\Clock
    app_main.submission.factory:
        class: App\Bundle\MainBundle\Services\Submission\SubmissionFactory
        arguments: [@app_main.clock]
    app_main.submission.writer:
        class: App\Bundle\MainBundle\Services\Submission\DoctrineWriter
        arguments: [@doctrine.orm.entity_manager, @app_main.submission.entity_converter]
    app_main.submission.reader:
        class: App\Bundle\MainBundle\Services\Submission\DoctrineReader
        arguments: [@doctrine.orm.entity_manager, @app_main.submission.entity_converter]
    app_main.submission.entity_converter:
        class: App\Bundle\MainBundle\Services\Submission\EntityConverter
