<?php

namespace App\Bundle\MainBundle\Entity\Vote;

use Doctrine\ORM\EntityRepository;

/**
 * CompiledRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompiledRepository extends EntityRepository
{
    /**
     * Retrieve compiled votes having the given references
     *
     * @param int[] $references
     *
     * @return Compiled[]
     */
    public function findCollection(array $references)
    {
        $builder = $this->createQueryBuilder('compiled');
        $builder
            ->where('compiled.reference IN (:references)')
            ->setParameter('references', $references)
        ;

        return $builder->getQuery()->getResult();
    }
}
