<?php

namespace App\Bundle\MainBundle\Entity\Vote;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    /**
     * Save the given entity in database
     *
     * @param Vote $vote
     */
    public function save(Vote $vote)
    {
        $this->getEntityManager()->persist($vote);
        $this->getEntityManager()->flush($vote);
    }

    /**
     * Check if a vote for the given object and username already exists
     *
     * @param int    $object
     * @param string $username
     *
     * @return bool
     */
    public function voteExists($object, $username)
    {
        $builder = $this->createQueryBuilder('vote');
        $builder
            ->where('vote.object = :object')
            ->andWhere('vote.username = :username')
            ->setParameter('object', $object)
            ->setParameter('username', $username)
        ;

        $vote = $builder->getQuery()->getOneOrNullResult();

        return ($vote !== null);
    }

    /**
     * Retrieve votes about given objects and username
     *
     * @param int[]  $objects
     * @param string $username
     *
     * @return Vote[]
     */
    public function findCollection($objects, $username)
    {
        $builder = $this->createQueryBuilder('vote');
        $builder
            ->where('vote.object IN (:objects)')
            ->andWhere('vote.username = :username')
            ->setParameter('objects', $objects)
            ->setParameter('username', $username)
        ;

        return $builder->getQuery()->getResult();
    }
}
