parameters:
    app_main.security.registration.hash_secret: %hash_secret%

services:
    app_main.security.command_bus:
        class: App\Component\Command\Bus
        arguments: [[@app_main.security.registration.confirm_handler, @app_main.security.registration.promote_handler]]
    app_main.security.registration.confirm_handler:
        class: App\Component\Security\Registration\ConfirmHandler
        arguments: [@app_main.security.user.writer, @app_main.security.registration.hash_generator]
    app_main.security.registration.promote_handler:
        class: App\Component\Security\User\PromoteHandler
        arguments: [@app_main.security.user.writer]
    app_main.security.registration.hash_generator:
        class: App\Component\Security\Registration\HMACHashGenerator
        arguments: ['%app_main.security.registration.hash_secret%']
    app_main.security.user.reader:
        class: App\Bundle\MainBundle\Services\Security\User\DoctrineReader
        arguments: [@doctrine.orm.entity_manager]
    app_main.security.user.writer:
        class: App\Bundle\MainBundle\Services\Security\User\DoctrineWriter
        arguments: [@doctrine.orm.entity_manager]
    app_main.security.user.user_provider:
        class: App\Bundle\MainBundle\Security\User\UserProvider
        arguments: [@app_main.security.user.reader]
    validator.app_main.security.registration.unique_email:
        class: App\Bundle\MainBundle\Validator\Constraints\Security\Registration\UniqueEmailValidator
        arguments: [@app_main.security.user.reader]
        tags:
            - { name: validator.constraint_validator, alias: app_main_security_registration_unique_email }
